name: Python Application CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv  # Install uv using pip
      - name: Install dependencies with uv
        run: |
          if [ -f requirements.txt ]; then uv pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          pytest dlt_bigquery/tests/test_utils.py
